image: node:15.2.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npx yarn install
    - npx yarn run build
  only:
    - develop
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - yarn
    - yarn test

deploy:
  stage: deploy
  before_script:
    - apt-get update -qq
  script:
    - apt-get install -y -qq lftp
    - ls -a
    - lftp -e "set ssl:verify-certificate false; mirror --reverse --verbose --delete build/ ./site/wwwroot ; quit" -u $USERNAME,$PASSWORD $HOST
  only:
    - develop
