import { AxiosInstance, AxiosRequestConfig } from 'axios';

export enum API_KEYS {
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  EDIT_PROFILE = 'EDIT_PROFILE',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  GET_WALLET_BALANCE = 'GET_WALLET_BALANCE',
  GET_STATIONS = 'GET_STATIONS',
  GET_ITEM_TYPES = 'GET_ITEM_TYPES',
  GET_ACTIVE_LGAS = 'GET_ACTIVE_LGAS',
  GET_SPECIAL_PACKAGES = 'GET_SPECIAL_PACKAGES',
  WALLET_TRANSACTIONS_SHIPMENT_HISTORY = 'WALLET_TRANSACTIONS_SHIPMENT_HISTORY',
  TRACK_SHIPMENT = 'TRACK_SHIPMENT',
  GET_HAULAGE = 'GET_HAULAGE',
  GET_HAULAGE_PRICE = 'GET_HAULAGE_PRICE',
  GET_SHIPMENT_DETAILS = 'GET_SHIPMENT_DETAILS',
  GET_DROPOFF = 'GET_DROPOFF',
  GET_OUTSTANDING_PAYMENTS = 'GET_OUTSTANDING_PAYMENTS',
  GET_SHIPMENT_IN_DISPUTE = 'GET_SHIPMENT_IN_DISPUTE',
  GET_PAYMENT_STATUS = 'GET_PAYMENT_STATUS',
  GET_HOME_DELIVERY_LOCATIONS = 'GET_HOME_DELIVERY_LOCATIONS',
  GET_SERVICE_CENTERS_BY_STATION = 'GET_SERVICE_CENTERS_BY_STATION',
  GET_SERVICE_CENTERS_BY_COUNTRY = 'GET_SERVICE_CENTERS_BY_COUNTRY',
  GET_IDENTIFICATION_TYPES = 'GET_IDENTIFICATION_TYPES',
  GET_ACTIVE_COUNTRIES = 'GET_ACTIVE_COUNTRIES',
  GET_SHIPMENT_MESSAGE = 'GET_SHIPMENT_MESSAGE',
  GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
  UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
  GET_STORES_BY_COUNTRY = 'GET_STORES_BY_COUNTRY',
  GET_INTERNATIONAL_SHIPMENTS = 'GET_INTERNATIONAL_SHIPMENTS',
  VERIFY_PAYMENT = 'VERIFY_PAYMENT',
  REPORT_ISSUES = 'REPORT_ISSUES',
  GET_PRICE = 'GET_PRICE',
  ADD_WAYBILL_PAYMENT_LOG = 'ADD_WAYBILL_PAYMENT_LOG',
  CREATE_SHIPMENT = 'CREATE_SHIPMENT',
  RESOLVE_DISPUTE = 'RESOLVE_DISPUTE',
  CANCEL_SHIPMENT = 'CANCEL_SHIPMENT',
  CANCEL_SHIPMENT_NOCHARGE = 'CANCEL_SHIPMENT_NOCHARGE',
  ADD_WALLET_PAYMENT_LOG = 'ADD_WALLET_PAYMENT_LOG',
  ADD_RATING = 'ADD_RATING',
  VERIFY_OTP = 'VERIFY_OTP',
  RESEND_OTP = 'RESEND_OTP',
  GET_DROPOFF_PRICE = 'GET_DROPOFF_PRICE',
  CREATE_DROPOFF = 'CREATE_DROPOFF',
  CANCEL_DROPOFF = 'CANCEL_DROPOFF',
  INTL_SHIPMENT_REQUEST_LIST = 'INTL_SHIPMENT_REQUEST_LIST',
  GET_DROP_OFF_LIST = 'GET_DROP_OFF_LIST',
  CREATE_INTL_SHIPMENT_REQUEST = 'CREATE_INTL_SHIPMENT_REQUEST',
  EDIT_INTL_SHIPMENT_REQUEST = 'EDIT_INTL_SHIPMENT_REQUEST',
  GET_INTL_SHIPMENT_MESSAGE = 'GET_INTL_SHIPMENT_MESSAGE',
  PROFILE_INTL_USER = 'PROFILE_INTL_USER',
  GET_VEHICLE_STATUS = 'GET_VEHICLE_STATUS',
  UPLOAD_IMAGE = 'UPLOAD_IMAGE',
  HANDLE_SHIPMENT = 'HANDLE_SHIPMENT',
  GET_PARTNER_DETAILS = 'GET_PARTNER_DETAILS',
  DELETE_SHIPMENT = 'DELETE_SHIPMENT',
}

export interface API_LIBRARY_OBJECT {
  instance: AxiosInstance;
  request: AxiosRequestConfig;
}

export type API_LIBRARY = {
  [x in API_KEYS]: API_LIBRARY_OBJECT;
};
