export interface FormSteps {
  name: string;
  label: string;
  caption: string;
}

export const formSteps: FormSteps[] = [
  {
    name: 'shipping-address',
    label: 'Shipping address',
    caption: '1',
  },
  {
    name: 'shipment-item',
    label: 'Shipment item',
    caption: '2',
  },
  {
    name: 'process-shipping',
    label: 'Process Shipping',
    caption: '3',
  },
];

export const shops = [
  {
    StoreId: 0,
    StoreName: 'Zara',
    Address: 'US',
    City: 'US',
    State: null,
    URL: 'https://www.zara.com/us/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/zara.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'Walmart',
    Address: 'Bentonville, Arkansas',
    City: 'Arkansas',
    State: null,
    URL: 'https://www.walmart.com/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/walmart.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'Old Navy',
    Address: 'US',
    City: 'US',
    State: null,
    URL: 'https://oldnavy.gap.com/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/oldnavy.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'H&M',
    Address: 'US',
    City: 'US',
    State: null,
    URL: 'https://www2.hm.com/en_us/index.html',
    storeImage: 'https://agilitysystemapidevm.azurewebsites.net/Images/hm.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'EBay',
    Address: 'San Jose, California',
    City: 'California',
    State: null,
    URL: 'https://www.ebay.com/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/ebay.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'Best Buy',
    Address: '7601 Penn Avenue S, Richfield, Minnesota, U.S.',
    City: 'Richfield',
    State: null,
    URL: 'https://www.bestbuy.com.mx/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/bestbuy.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'Asos',
    Address: 'US',
    City: 'US',
    State: null,
    URL: 'https://www.asos.com/us/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/asos.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
  {
    StoreId: 0,
    StoreName: 'Amazon',
    Address: 'NU410 Terry Ave N SeattleLL',
    City: 'Seattle',
    State: null,
    URL: 'https://www.amazon.com/',
    storeImage:
      'https://agilitysystemapidevm.azurewebsites.net/Images/amazon.png',
    Imagebyte: null,
    CountryId: 0,
    CountryName: null,
    DateCreated: '0001-01-01T00:00:00',
    DateModified: '0001-01-01T00:00:00',
    IsDeleted: false,
    RowVersion: null,
  },
];
